name: Check application status
on:
  workflow_dispatch:
jobs:
  check-status:
    runs-on: self-hosted
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run E2E tests
      run: pytest test/e2e -v

    - name: Run UI Tests
      run: make test-ui

    - name: Check Status
      run: curl --verbose https://getrapid.link/status
