name: Check application status
on:
  workflow_dispatch:
jobs:
  check-status:
    runs-on: self-hosted
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run E2E tests
      run: |
        pip install -r requirements.txt
        pytest -v

    - name: Check connection
      run: curl --verbose https://getrapid.link/status
