name: Check status
on:
  workflow_dispatch:
jobs:
  get-config:
    runs-on: self-hosted
    steps:
    - name: Get Config
      run: curl ifconfig.me

  check-status:
    runs-on: self-hosted
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install -r requirements.txt
        pytest -v

    - name: Check Status
      run: curl --verbose https://getrapid.link/status
