name: rAPId Deployment

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Log commit SHA
        run: echo $GITHUB_SHA

      - name: Export env vars
        run:
          cp ./.github/.github.env .env

      # Make sure to have a new line in .github.env. Otherwise, it would append the DOMAIN_NAME
      # to the last item
      - name: Export DOMAIN_NAME
        run:
          echo DOMAIN_NAME=${{ secrets.DOMAIN_NAME }} >> .env

      - name: Export DATA_BUCKET
        run:
          echo DATA_BUCKET=${{ secrets.DATA_BUCKET }} >> .env

      - name: Export AWS_ACCOUNT
        run:
          echo AWS_ACCOUNT=${{ secrets.AWS_ACCOUNT }} >> .env

      - name: Export AWS_REGION
        run:
          echo AWS_REGION=${{ secrets.AWS_REGION }} >> .env

      - name: Export AWS_DEFAULT_REGION
        run:
          echo AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} >> .env

      - name: Export AWS_KEY_ID
        run: |
          aws configure list
          aws configure get aws_access_key_id
          echo "::add-mask::${{aws configure get aws_access_key_id}}"
          echo AWS_ACCESS_KEY_ID=${{aws configure get aws_access_key_id}} >> .env

      - name: Check .env
        run:
          cat .env

      - name: Build Image
        run: make create-runtime-env

      - name: Security Checks
        run: make security

      - name: Static Analysis
        run: make lint

      - name: Run Tests
        run: make test-coverage

      - name: Tag and Upload
        run: make tag-and-upload

      - name: Check image scan for vulnerabitities
        run: make scan-for-vulns-and-tag

      - name: Tag PROD candidate
        run: make tag-prod-candidate

      - name: Deploy new image to Prod
        run: make app-live-in-prod

      # Prevent check-app-is-running below from timing out by adding extra time
      - name: Allow time for the application to start
        run: sleep 120

      - name: Wait for application to be running
        id: await-running-app
        run: make check-app-is-running

#     Skip E2E tests while they are being fixed
      - name: Run E2E tests
        id: e2e-tests
        run: make test-e2e

      - name: Tag image as failure
        if: always() && steps.await-running-app.conclusion == 'failure' || steps.e2e-tests.conclusion == 'failure'
        run: make tag-prod-failure

      - name: Clean Docker context
        if: always()
        run: make clean-pipeline-docker-context
