name: Scheduled vulnerability scan results check
on:
  schedule:
    - cron: "0 9,15 * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Check for vulnerabilities
        run: make scheduled-prod-scan
